# Generated by Django 4.2 on 2023-04-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id']},
        ),
    ]
