# Generated by Django 4.2 on 2023-04-29 09:49

import championship.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('image', models.ImageField(upload_to='championship')),
                ('sort', models.IntegerField(default=championship.models.last_sort_number, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_years', models.CharField(max_length=25, blank=True)),
                ('match_days', models.CharField(max_length=15, default='6-7')),
                ('start_date', models.DateField(blank=True)),
                ('is_started', models.BooleanField(default=False)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season', to='championship.championship', blank=True)),
            ],
        ),
    ]
