# Generated by Django 4.2 on 2023-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['sort']},
        ),
        migrations.AlterField(
            model_name='championship',
            name='image',
            field=models.ImageField(upload_to='championship/'),
        ),
    ]
